### ISSUE TITLE
Incorrect documenation for guestentries.php?

### ISSUE THREAD

**Issue by esseb** [pixelandtonic/GuestEntries#10]
The [documentation](https://github.com/pixelandtonic/GuestEntries/blob/master/README.md#configuration) says I can override the "Guest Entries’ config settings" by creating a new `guestentries.php` file in my `craft/config/` folder.

I have done this, and the file contains:
```
<?php

return array(
    'entryVariable' => 'commentEntry',
);
```

No change, the entry variable does not change.

If I instead edit `craft/plugins/guestentries/config.php` to look like this:
```
<?php

return array(
    /**
     * The name of the variable that submitted entries should be assigned to when the template is reloaded
     * in the event of a validation error.
     */
    'entryVariable' => 'commentEntry',
);
```

everything works fine.

Is the documentation just out of date and I'm actually meant to edit `craft/plugins/guestentries/config.php` or is there a bug with reading the config from `guestentries.php`?

**Comment by takobell** [comment]
Documentation is incorrect... fixed in https://github.com/pixelandtonic/GuestEntries/commit/181aba2e3333ac9defd1460e093644a7864429a2
