### ISSUE TITLE
POST param “sectionId” doesn’t exist.

### ISSUE THREAD

**Issue by myothernickname** [pixelandtonic/GuestEntries#20]
Not sure what Im doing wrong here. Using the default form from the docs.. 
Set my sectionId, but im getting this error once i submit. 
POST param “sectionId” doesn’t exist.

Any help would be appreciated. 
Thanks

Craft CMS 2.6.2964

**Comment by myothernickname** [comment]
`<form method="post" action="" accept-charset="UTF-8">
    {{ getCsrfInput() }}
    <input type="hidden" name="action" value="guestEntries/saveEntry">
    <input type="hidden" name="redirect" value="success">
    <input type="hidden" name="opiniones" value="3">
    <label for="title">Title</label>
    <input id="title" type="text" name="title">
    <label for="body">Body</label>
    <textarea id="body" name="fields[body]"></textarea>
    <input type="submit" value="Publish">
</form>
`
-opiniones is the section id. 
-Have the section allowed for guest posts, with a user selected.
-Only other plugin Im using is the contact form 1.81
-running Craft CMS 2.6.2964 Personal

thanks again.

**Comment by takobell** [comment]
`<input type="hidden" name="opiniones" value="3">` should be `<input type="hidden" name="sectionId" value="3">`

**Comment by myothernickname** [comment]
I put it this way because I thought It needed the section ID. Guess I
created a second issue trying to fix the first one.
My initial one:

Default form from the docs,
hit submit, redirects to a 404 page. thing gets posted.
Im not logged in by the way.

Thanks
