### ISSUE TITLE
"Validate Entry" lightswitch in plugin settings remains true always

### ISSUE THREAD

**Issue by danielparas** [pixelandtonic/GuestEntries#3]
Hi I think there might be a small bug within the plugin settings area:

1. Go to Guest Entries plugin settings
2. Set the "Validate Entry" setting for a section to false (lightswitch off)
3. Press save
4. Re-visit the entries plugin settings to find that light switch is on again i.e. "Validate Entry" setting did not save to false.

Thanks!

**Comment by takobell** [comment]
Thanks... just pushed a fix for that!
