### ISSUE TITLE
Entry not visible in entries list in CP

### ISSUE THREAD

**Issue by bartrylant** [pixelandtonic/GuestEntries#7]
Hi

When I use this plugin, I don't see the entry in the control panel under the "entries" tab (entries > all entries). The strange this is: it is in the database, it also shows up on the dashboard (in the recent content widget), and if I click it there, I can edit it. It's just missing from the entries page.

**Comment by takobell** [comment]
I'm guessing you've got the "Entries Enabled By Default?" plugin setting set to off and > 50 entries in the section already.  The entry index page will put any disabled entries at the bottom of the list and that is probably off-screen for you.
