### ISSUE TITLE
Managing errors

### ISSUE THREAD

**Issue by cole007** [pixelandtonic/GuestEntries#8]
Am using GuestEntries in an add-on to permit site visitors to add a 'comment' to an existing entry.
The error I am experiencing is if an error is returned - eg if a required field is not filled - the returned template is treating the submitted Guest entry/comment and not the Source entry that is being commented against as an entry object. 

This changes the title and contents of the page being requested/shown.

Any thoughts on how to resolve this issue appreciated (aside from front-loading my error validation to the client-side)

**Comment by takobell** [comment]
I'm not following. Can you elaborate more with some code examples?  You might be better of posting this on Craft Stack Exchange as it doesn't sound like a plugin specific bug.

**Comment by ianisted** [comment]
I've build a comment system using Guest Entries too. If I set fields to be required and don't fill them in in the front-end, I get the following error.

Fatal error: Class 'Craft\GuestEntriesEvent' not found in ****/craft/plugins/guestentries/controllers/GuestEntriesController.php on line 136

**Comment by ianisted** [comment]
Cole did you manage to fix your issue?

**Comment by cole007** [comment]
Hi @ianisted 

Alas not - ended up using this as an opportunity to write my own plugin.
Happy to send over the code if interested but very specific to client so would need some tweaking.

Cole

**Comment by ianisted** [comment]
Thanks @cole007, it would be great to take a look if you don't mind. If I find a solution to the error I'll let you know :)

**Comment by esseb** [comment]
This issue occurs if the form does not have a redirect parameter:
`<input type="hidden" name="redirect" value="success">`

On errors, the article reloads but this time with `entry` referring to the guest entry and not the original article.

Can be fixed by changing the `entryVariable` config setting, although see https://github.com/pixelandtonic/GuestEntries/issues/10
