### ISSUE TITLE
Populating Tables/Matrix Fields

### ISSUE THREAD

**Issue by ianisted** [pixelandtonic/GuestEntries#9]
Is there a way to populate a Matrix Field or a Table using the GuestEntries plugin?

Not sure what the name field should be set to if it's already possible.

**Comment by takobell** [comment]
http://craftcms.stackexchange.com/a/13621/57

**Comment by ianisted** [comment]
Hi Brad. Finally managed to get this resolved. Seems there was some confusion around the column handles for tables.

This is possibly a bug, or most likely a discrepancy in the [documentation](https://straightupcraft.com/articles/craft-cms-field-guide-twig?view=input). Have posted my findings here. http://craftcms.stackexchange.com/a/13684/475

**Comment by stevepiron** [comment]
Hi, I'm trying to do the same with Craft 3. I'm not sure what's wrong with my markup but it doesn't work.

```html
<input type="hidden" name="matrixFieldHandle[new1][type]" value="matrixBlockHandle">
<input type="text" name="matrixFieldHandle[new1][fields][fieldHandle]" value="data">
```

I've intended to do it that way because of [this answer](https://craftcms.stackexchange.com/a/21865/7824) by @brandonkelly on Stack Exchange.
